---
title: ''
format: pdf
bibliography: ../references.bib
editor:
  markdown:
    references: 
      location: block
      prefix: "abstract"
---

# Abstract {.unnumbered}

Correlation does not imply causality, yet sport scientist are often interested in causal relationships without being able to conduct randomized controlled trials, the gold standard of causal analysis. Instead, they rely on observational or quasi-experimental data, where causal analysis is more complicated and requires specialized techniques. In this thesis, I introduce these methods of causal inference to the field of sport science. I present essential ideas of causal inference using directed acyclic graphs and demonstrate the utility of causal reasoning by revisiting two published observation studies from sport science. Introducing methods of causal inference in sport science enhances the field by limiting biases and providing new opportunities for research. This approach requires a thoughtful consideration of the causal network underlying a research phenomenon, necessitating a combination of both methodological and domain expertise. Applying causal inference methods is part of a larger five-step analytical framework proposed herein, which includes clearly stating a research goal, defining an empirical target quantity for analysis, using appropriate estimation procedures, investigating the robustness of results, and transparently communicating research findings and limitations.

\newpage

# Zusammenfassung (German Abstract) {.unnumbered}

Korrelation impliziert keine Kausalität, dennoch sind Sportwissenschaftler oft an kausalen Zusammenhängen interessiert, ohne den Goldstandard einer randomisierte kontrollierter Studien durchführen zu können. Stattdessen müssen sie sich auf Beobachtungs- oder quasi-experimentelle Daten verlassen, bei denen die kausale Analysen komplizierter ist und spezielle Techniken erfordern. In dieser Arbeit stelle ich diese Methoden aus dem Bereich des "causal inference" in Bezug auf die Sportwissenschaft vor. Ich präsentiere wesentliche Ideen des "causal inference" unter Verwendung gerichteter azyklischer Graphen und demonstriere den Nutzen kausalen Denkens durch die Neubetrachtung zweier veröffentlichter Beobachtungsstudien aus der Sportwissenschaft. Die Einführung von "causal inference" Methoden in der Sportwissenschaft reduziert systematische Fehler in Untersuchungen und bietet neue Forschungsmöglichkeiten. Der Ansatz erfordert eine sorgfältige Berücksichtigung des kausalen Netzwerks, das einem Forschungsphänomen zugrunde liegt, und erfordert daher eine Kombination aus methodischem und fachspezifischem Wissen. Die Anwendung von "causal inference" Methoden ist Teil eines größeren, hier vorgeschlagenen fünfstufigen analytischen Rahmens, der die klare Formulierung eines Forschungsziels, die Definition einer empirischen Zielgröße für die Analyse, die Verwendung geeigneter Analyseverfahren, die Untersuchung der Robustheit der Ergebnisse und die transparente Kommunikation der Forschungsergebnisse und ihrer Limitationen umfasst.


