---
title: ''
format: pdf
bibliography: ../references.bib
editor:
  markdown:
    references: 
      location: block
      prefix: "math"
---

### Probability Theory

A random variable is a property we cannot absolutely predict. The probability of the random variable $X$ is given by $Pr(X)$. An event is the assignment of a value to a random variable. The probability of event $A$ given that event $B$ has occurred is the conditional probability of $A$ given $B$ and is denoted by $Pr(A|B)$. The events $A$ and $B$ are statistically independent if the observation of $B$ does not alter the probability of $A$, or $Pr(A|B) = Pr(A)$. Another way to note independence is $A \perp \!\!\! \perp  B$. Two events are conditionally independent if they are independent given a third event $C$, implying that $Pr(A|B,C) = Pr(A|C)$. This conditional independence can also be denoted as $A \perp \!\!\! \perp  B|C$. The expected value of a random variable $X$ is the weighted probability of the values it can take, denoted by $E(X)$.

### Potential Outcome Notation

For simplicity, we use a binary variable that takes on the value 0 if a unit $i$ received no treatment and the value 1 if the unit $i$ received treatment. Every unit $i$ has two potential outcomes $Y_i^0$ and $Y_i^1$. These outcomes are hypothetical, as each unit only can or cannot receive a treatment and therefore only one of the two potential outcomes is realized. The observed $Y_i$ can be defined as $Y_i = (D_i-1)Y_i^0 + D_iY_i^1$ with $D_i$ as the unit-specific treatment indicator. The individual causal effect $\delta_i$ of the treatment is defined as a comparison of the two potential outcomes for each unit $\delta_i = Y_i^1 - Y_i^0$. This poses a problem, as we never observe both potential outcomes for a single unit simultaneously and thus cannot calculate $\delta_i$. The average treatment effect is defined by $E(\delta_i) = E(Y_i^1 - Y_i^0) = E(Y_i^1) - E(Y_i^0)$. Making the strong assumptions that $E(Y_i^1|D = 0) = E(Y_i^1|D = 1)$ and $E(Y_i^0|D = 0) = E(Y_i^0|D = 1)$ we get an unbiased estimate of the average treatment effect by calculating the simple differences in means $E(Y_i^1|D = 1) - E(Y_i^0|D = 0)$, which are both observed quantities. Or in other words, we obtain an unbiased estimate of the causal treatment effect by comparing the mean of the treatment group and the mean of the untreated group, if we assume that the mean of the treatment group equals the mean that the untreated group would have had if they had received the treatment (and vice versa). This is sometimes called the exchangeability assumption. It implies, that the assignment of treatment was independent of the potential outcomes, or $(Y^0, Y^1)\perp \!\!\! \perp D$, something that could, for example, be guaranteed by randomization. Often the strict independence of assignment and potential outcomes only holds when conditioning on another variable (set) $W$ that influenced the randomization process. The independence assumption then changes to an assumption of conditional independence $(Y^0, Y^1)\perp \!\!\! \perp D | W$. As long $W$ is observed, we can use appropriate strategies such as sub-classification, matching, or conditioning, to get an unbiased estimate of $\delta_i$ given the conditional independence assumption.

<!-- assumptions? -->
