---
title: ''
format: pdf
bibliography: ../references.bib
editor:
  markdown:
    references: 
      location: block
      prefix: "methods"
---

# Methods

For this thesis I reviewed two examplic research articles from sport science [@malisoux2015; @kruseman2005] from a causal inference point of view. I chose them based on a non-systematic research, implicitly following the following criteria: (1) observational study research design; (2) from a subfield (endurance running) I feel confident in having enough background knowledge to discuss potential causal models; (3) causal aim; (4) representative for current sport science (i.e., published in respected journals and having received scientific attention in form of citations). I furthermore considered the potential to discuss difference causal aspects in the studies, and thus chose two studies differing in their aim and methods used. Due to the unsystematic search and screening of studies, the final choice of studies was subjective, but I believe they were not just good for me to make a point, but also represent a valid example of sport science research.

This thesis was registered before it start using a free form preregistration published on the Open Science Framework [@foster2017] under the following link: LINK HERE. However, as this thesis is mainly conceptual, writing a preregistration was challenging. It was not possible to make any concrete statements about the planed research. The published preregistration captured my ideas for this thesis with the causal inference knowledge I had before starting to write it. Since then both my knowledge and my ideas of the thesis have developed, to the extend that ultimately this final thesis shows major deviations from its preregistration.

Originally I planed to demonstrate techniques and principles of causal inference on a previously published data set from endurance running. However during the process of writing I realized that the data set is not adequate to perform causal analyses, and that it is rather impossible (and not useful) to demonstrate several general principles of causal inference on a single data set; instead it is more helpful to work on a concrete research example and apply the appropriate causal inference techniques. Therefore, I decided to revisit two published studies from a causal inference view point, something I had not considered when writing the preregistration. Additionally, I originally planed to demonstrate the process of developing a causal model by creating a causal model of endurance performance. During the writing of the thesis I realized that general causal model rarely exist (especially if the concept investigated is complex), but that appropriate causal models always depend on the exact research question and context (see @sec-complex for a discussion). Thus, I did not develop a causal model for endurance performance, but developed potential causal model for the example articles I discuss. Finally, the preregistration focused mainly on the graphical model approach to causal inference. This was primarily because that was my first entry to causal inference and at the point of writing the preregistration I was only partly aware of other approaches. While the final thesis still focuses on graphical models in the theoretical background section, I also thoroughly discuss methods more often attributed to other causal inference frameworks (e.g., the identification strategies in @sec-ident that are often seen as related to the potential outcome framework). In a way, this thesis also demonstrates the process of individual acquaintance with a research field and the difficulties in pre-planing conceptual work.

I conducted all analyses in this thesis using R version 4.4.0 [@r2024] in the RStudio IDE version 2024.4.0.735 [@positteam2024]. The thesis was written in Quarto version 1.3.450 [@allaire2023]. The default settings and attached packages are documented in Appendix @sec-tech. The DAGs in this thesis were drawn using the ggdag R package [@barrett2024], which is based on the software daggity [@textor2016]. All source code of this project is available at [GitHub](https://github.com/smnnlt/causal-inference-sport).
